arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - base_to_link1
     - link1_to_link2
     - link2_to_link3
     - link3_to_link4
     - link4_to_link5
     - link5_to_link6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      base_to_link1: {trajectory: 0.1, goal: 0.1}
      link1_to_link2: {trajectory: 0.1, goal: 0.1}
      link2_to_link3: {trajectory: 0.1, goal: 0.1}
      link3_to_link4: {trajectory: 0.1, goal: 0.1}
      link4_to_link5: {trajectory: 0.1, goal: 0.1}
      link5_to_link6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
